FROM recipes-base AS build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY . ./
# ENV NODE_ENV=production
RUN yarn
RUN yarn build
 
FROM nginx:1.23.1-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]