FROM recipes-base

WORKDIR /app
# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
# COPY --from=recipes-base /node_modules ./app/node_modules
COPY package.json ./
COPY yarn.lock ./
# add app
COPY . ./

RUN yarn

# start app
CMD ["yarn", "start"]